

/* APP */
export const START_LOADING_APP = 'START_LOADING_APP'
export const END_LOADING_APP = 'END_LOADING_APP'

/* 充电桩 */
export const START_LOADING_POWER = 'START_LOADING_POWER'
export const END_LOADING_POWER = 'END_LOADING_POWER'

/* 售货机 */
export const START_LOADING_SELL = 'START_LOADING_SELL'
export const END_LOADING_SELL = 'END_LOADING_SELL'