export const START_LOADING_APP = "START_LOADING_APP"
export const END_LOADING_APP = "END_LOADING_APP"

export const START_LOADING_COMPANY = "START_LOADING_COMPANY"
export const END_LOADING_COMPANY = "END_LOADING_COMPANY"

export const START_LOADING_DICT = "START_LOADING_DICT"
export const END_LOADING_DICT = "END_LOADING_DICT"

export const START_LOADING_DEVICE = "START_LOADING_DEVICE"
export const END_LOADING_DEVICE = "END_LOADING_DEVICE"