export const START_LOADING_APP = "START_LOADING_APP"
export const END_LOADING_APP = "END_LOADING_APP"

export const START_LOADING_SYSTEM = "START_LOADING_SYSTEM"
export const END_LOADING_SYSTEM = "END_LOADING_SYSTEM"

export const START_LOADING_BASE = "START_LOADING_BASE"
export const END_LOADING_BASE = "END_LOADING_BASE"

export const START_LOADING_PROJECT = "START_LOADING_PROJECT"
export const END_LOADING_PROJECT = "END_LOADING_PROJECT"