export const START_LOADING_APP = "START_LOADING_APP"
export const END_LOADING_APP = "END_LOADING_APP"

export const START_LOADING_SYSTEM = "START_LOADING_SYSTEM"
export const END_LOADING_SYSTEM = "END_LOADING_SYSTEM"

export const START_LOADING_PERSON = "START_LOADING_PERSON"
export const END_LOADING_PERSON = "END_LOADING_PERSON"