export const LOADING_DATA_START = "LOADING_DATA_START"
export const LOADING_DATA_END = "LOADING_DATA_END"

export const LOADING_PROJECT_START = "LOADING_PROJECT_START"
export const LOADING_PROJECT_END = "LOADING_PROJECT_END"

export const LOADING_PARK_START = "LOADING_PARK_START"
export const LOADING_PARK_END = "LOADING_PARK_END"